In [1]:
#a list
[[123,12,123,12,33],[],[]]

[[123, 12, 123, 12, 33], [], []]

In [5]:
import numpy
n=numpy.arange(27)
type(n)

numpy.ndarray

In [6]:
n.reshape(3,9) 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [7]:
n.reshape(3,3,3) #3 dimensional array


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [8]:
#numpy array
m = numpy.asarray([[123,12,123,12,33],[],[]])
m

array([list([123, 12, 123, 12, 33]), list([]), list([])], dtype=object)

In [9]:
#import cv2

In [12]:
import cv2
#using cv2 to load images
im_g = cv2.imread("./sample_data/smallgray.png",0) #0 = grayscale, 1 = bgr.
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [17]:
im_c = cv2.imread("./sample_data/icons8-Planetarium-48.png", 1)
print(im_c[3])

[[  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [175 165 143]
 [174 164 144]
 [175 159 143]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]]


In [18]:
#write an image
#cv2.imwrite("./sample_data/newsmgray.png", im_g)

True

In [19]:
#indexing, slicing, iterating
a = [1,2,3]
a[0:2] # the first 2

[1, 2]

In [21]:
im_g[0:2] #first 2 rows

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [22]:
im_g[0:2, 0:2] #first 2 rows and the first 2 columns

array([[187, 158],
       [198, 125]], dtype=uint8)

In [23]:
im_g.shape #get the shape

(3, 5)

In [24]:
#iterate through numpy array
for i in im_g:
    print(i)  #where i is the row

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [25]:
#transpose to iterate through columns
for i in im_g.T: 
    print(i)  #where i is the column

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [26]:
#access each value by flattening the array
for i in im_g.flat:
    print(i) 

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [27]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [31]:
#stacking numpy arrays
#put the arrays in a tuple
imsh = numpy.hstack((im_g, im_g)) #stack 2 numpy arrays horizontally
imsh

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [32]:
#vertically stack 2 arrays
imsv = numpy.vstack((im_g, im_g))
imsv

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [37]:
#splitting arrays into 2 smaller arrays
lst2 = numpy.hsplit(imsh, 2)
lst2


[array([[187, 158],
        [198, 125],
        [209, 134]], dtype=uint8), array([[104, 121],
        [255, 255],
        [255,  97]], dtype=uint8), array([[143, 187],
        [147, 198],
        [182, 209]], dtype=uint8), array([[158, 104],
        [125, 255],
        [134, 255]], dtype=uint8), array([[121, 143],
        [255, 147],
        [ 97, 182]], dtype=uint8)]

In [38]:
lst5 = numpy.hsplit(imsh, 5) #split into 5 arrays
lst5

[array([[187, 158],
        [198, 125],
        [209, 134]], dtype=uint8), array([[104, 121],
        [255, 255],
        [255,  97]], dtype=uint8), array([[143, 187],
        [147, 198],
        [182, 209]], dtype=uint8), array([[158, 104],
        [125, 255],
        [134, 255]], dtype=uint8), array([[121, 143],
        [255, 147],
        [ 97, 182]], dtype=uint8)]

In [40]:
#vertical splitting
lstv = numpy.vsplit(imsv, 2)
lstv #produces a list of arrays


[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [42]:
lstv[0] #access the first element in the list

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)