In [1]:
#a list
[[123,12,123,12,33],[],[]]

[[123, 12, 123, 12, 33], [], []]

In [5]:
import numpy
n=numpy.arange(27)
type(n)

numpy.ndarray

In [6]:
n.reshape(3,9) 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [7]:
n.reshape(3,3,3) #3 dimensional array


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [8]:
#numpy array
m = numpy.asarray([[123,12,123,12,33],[],[]])
m

array([list([123, 12, 123, 12, 33]), list([]), list([])], dtype=object)

In [9]:
#import cv2

In [12]:
import cv2
#using cv2 to load images
im_g = cv2.imread("./sample_data/smallgray.png",0) #0 = grayscale, 1 = bgr.
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [17]:
im_c = cv2.imread("./sample_data/icons8-Planetarium-48.png", 1)
print(im_c[3])

[[  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [175 165 143]
 [174 164 144]
 [175 159 143]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]]


In [18]:
#write an image
cv2.imwrite("./sample_data/newsmgray.png", im_g)

True